add_cus_dep('glo', 'gls', 0, 'run_makeglossaries');
add_cus_dep('acn', 'acr', 0, 'run_makeglossaries');

$out_dir = 'out';
$private_data_file = "$out_dir/private-data.tex";

no warnings 'redefine';
sub run_makeglossaries {
  my ($base_name, $path) = fileparse( $_[0] ); #handle -outdir param by splitting path and file, ...
  pushd $path; # ... cd-ing into folder first, then running makeglossaries ...

  if ( $silent ) {
      system "makeglossaries -q '$base_name'"; #unix
  }
  else {
      system "makeglossaries '$base_name'"; #unix
  };

  popd; # ... and cd-ing back again
}
use warnings 'redefine';

sub enrico_wants_personal_data {
  return env_true('PRIVATE');
}

sub env_true {
  my ($name) = @_;
  return 0 unless defined $ENV{$name};
  return $ENV{$name} =~ /^(?:1|true|yes|on)$/i;
}

sub read_dotenv_value {
  my ($name) = @_;
  return undef unless open(my $fh, '<', '.env');

  while (my $line = <$fh>) {
    chomp $line;
    $line =~ s/\r$//;
    next if $line =~ /^\s*(?:#|$)/;
    next unless $line =~ /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/;

    my ($key, $value) = ($1, $2);
    next unless $key eq $name;

    if ($value =~ /^"(.*)"$/ || $value =~ /^'(.*)'$/) {
      $value = $1;
    }

    close($fh);
    return $value;
  }

  close($fh);
  return undef;
}

sub latex_escape {
  my ($value) = @_;
  $value =~ s/([\\{}#%&_\$])/\\$1/g;
  return $value;
}

sub sync_private_data {
  my $wants_personal_data = enrico_wants_personal_data();
  my @private_values = (
    ['PHONE_NUMBER', 'PrivatePhoneNumber'],
    ['LUIGI_NUMBER', 'PrivateLuigiNumber'],
    ['MARCO_NUMBER', 'PrivateMarcoNumber'],
  );

  if ($wants_personal_data) {
    my @missing = ();
    my @commands = ();

    for my $private_value (@private_values) {
      my ($env_name, $command_name) = @$private_value;
      my $value = read_dotenv_value($env_name);

      if (!defined($value) || !length($value)) {
        push @missing, $env_name;
        next;
      }

      push @commands, "\\newcommand{\\$command_name}{" . latex_escape($value) . "}\n";
    }

    if (!@missing) {
      mkdir $out_dir unless -d $out_dir;
      open(my $fh, '>', $private_data_file) or die "Cannot write $private_data_file: $!";
      print $fh "% Generated by latexmk from .env. Do not commit.\n";
      print $fh @commands;
      close($fh);
      return;
    }

    if (-e '.env') {
      warn "latexmk: missing private env value(s): " . join(', ', @missing) . "; building public CV\n";
    }
  }

  unlink $private_data_file if -e $private_data_file;
}

sync_private_data();

push @generated_exts, 'glo', 'gls', 'glg', 'glsdefs';
push @generated_exts, 'acn', 'acr', 'alg';
push @generated_exts, 'synctex.gz';
$clean_ext .= ' %R.ist %R.xdy %R.bbl';

#$pdflatex = 'lualatex -interaction=nonstopmode -synctex=1 -shell-escape';
if (env_true('PRIVATE')) {
  $pdflatex = 'pdflatex -interaction=nonstopmode -synctex=1 -shell-escape %O "\def\PrivateBuild{1}\input{%S}"';
  $lualatex = 'lualatex -interaction=nonstopmode -synctex=1 -shell-escape %O "\def\PrivateBuild{1}\input{%S}"';
}
else {
  $pdflatex = 'pdflatex -interaction=nonstopmode -synctex=1 -shell-escape %O %S';
  $lualatex = 'lualatex -interaction=nonstopmode -synctex=1 -shell-escape %O %S';
}

# $pdf_mode = 4;
$pdf_mode = 1;

$pdf_previewer = 'xdg-open'
